# Generated by Django 4.0.3 on 2022-04-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_avatar_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='additional_description',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avatar',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
