# Generated by Django 4.0.1 on 2022-03-11 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0002_autor_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='investigation_area',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
