# Generated by Django 4.0.1 on 2022-03-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0003_project_investigation_area'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='publishing_company',
            new_name='PublishingCompany',
        ),
    ]
