# Generated by Django 4.0.1 on 2022-03-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0004_rename_publishing_company_publishingcompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publishingcompany',
            options={'ordering': ['-publishing_name'], 'verbose_name': 'Editorial', 'verbose_name_plural': 'Editoriales'},
        ),
    ]
