# Generated by Django 4.0.3 on 2022-03-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0007_delete_autor_delete_publishingcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ImageField(default=20220315, upload_to='mainblog', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
