# Generated by Django 4.0.3 on 2022-04-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainblog', '0009_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='autor',
            field=models.CharField(default=1406, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(default=1406, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.CharField(default=1406, max_length=75),
            preserve_default=False,
        ),
    ]
